//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPBzadanie1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionsWithStrokesObject", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.RegionsWithStrokes")]
    [System.SerializableAttribute()]
    public partial class RegionsWithStrokesObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.RegionWithStrokes[] RegionsWithStrokesListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.RegionWithStrokes[] RegionsWithStrokesList {
            get {
                return this.RegionsWithStrokesListField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionsWithStrokesListField, value) != true)) {
                    this.RegionsWithStrokesListField = value;
                    this.RaisePropertyChanged("RegionsWithStrokesList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegionWithStrokes", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.RegionsWithStrokes")]
    [System.SerializableAttribute()]
    public partial class RegionWithStrokes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DPIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.SurveyRegion RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.InquiryStroke[] StrokesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DPI {
            get {
                return this.DPIField;
            }
            set {
                if ((this.DPIField.Equals(value) != true)) {
                    this.DPIField = value;
                    this.RaisePropertyChanged("DPI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.SurveyRegion Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.InquiryStroke[] Strokes {
            get {
                return this.StrokesField;
            }
            set {
                if ((object.ReferenceEquals(this.StrokesField, value) != true)) {
                    this.StrokesField = value;
                    this.RaisePropertyChanged("Strokes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyRegion", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Survey")]
    [System.SerializableAttribute()]
    public partial class SurveyRegion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSeriesValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictionariesIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DpiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FontNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FontSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcrCustomerDictionaryGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCheckboxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDataSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsObligatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MultipleWordsRecognitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfCharsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PossibleCharactersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.SurveyRegionKey RegionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyAnalyseTemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopLeft_xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TopLeft_yField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.TypeOfRegion TypeOfRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSeriesValue {
            get {
                return this.DataSeriesValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSeriesValueField, value) != true)) {
                    this.DataSeriesValueField = value;
                    this.RaisePropertyChanged("DataSeriesValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultValue {
            get {
                return this.DefaultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultValueField, value) != true)) {
                    this.DefaultValueField = value;
                    this.RaisePropertyChanged("DefaultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DictionariesID {
            get {
                return this.DictionariesIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DictionariesIDField, value) != true)) {
                    this.DictionariesIDField = value;
                    this.RaisePropertyChanged("DictionariesID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Dpi {
            get {
                return this.DpiField;
            }
            set {
                if ((this.DpiField.Equals(value) != true)) {
                    this.DpiField = value;
                    this.RaisePropertyChanged("Dpi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalSystemId {
            get {
                return this.ExternalSystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalSystemIdField, value) != true)) {
                    this.ExternalSystemIdField = value;
                    this.RaisePropertyChanged("ExternalSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FontName {
            get {
                return this.FontNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FontNameField, value) != true)) {
                    this.FontNameField = value;
                    this.RaisePropertyChanged("FontName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FontSize {
            get {
                return this.FontSizeField;
            }
            set {
                if ((this.FontSizeField.Equals(value) != true)) {
                    this.FontSizeField = value;
                    this.RaisePropertyChanged("FontSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IcrCustomerDictionaryGuid {
            get {
                return this.IcrCustomerDictionaryGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.IcrCustomerDictionaryGuidField, value) != true)) {
                    this.IcrCustomerDictionaryGuidField = value;
                    this.RaisePropertyChanged("IcrCustomerDictionaryGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCheckbox {
            get {
                return this.IsCheckboxField;
            }
            set {
                if ((this.IsCheckboxField.Equals(value) != true)) {
                    this.IsCheckboxField = value;
                    this.RaisePropertyChanged("IsCheckbox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDataSeries {
            get {
                return this.IsDataSeriesField;
            }
            set {
                if ((this.IsDataSeriesField.Equals(value) != true)) {
                    this.IsDataSeriesField = value;
                    this.RaisePropertyChanged("IsDataSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsObligatory {
            get {
                return this.IsObligatoryField;
            }
            set {
                if ((this.IsObligatoryField.Equals(value) != true)) {
                    this.IsObligatoryField = value;
                    this.RaisePropertyChanged("IsObligatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MultipleWordsRecognition {
            get {
                return this.MultipleWordsRecognitionField;
            }
            set {
                if ((this.MultipleWordsRecognitionField.Equals(value) != true)) {
                    this.MultipleWordsRecognitionField = value;
                    this.RaisePropertyChanged("MultipleWordsRecognition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfChars {
            get {
                return this.NumberOfCharsField;
            }
            set {
                if ((this.NumberOfCharsField.Equals(value) != true)) {
                    this.NumberOfCharsField = value;
                    this.RaisePropertyChanged("NumberOfChars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PossibleCharacters {
            get {
                return this.PossibleCharactersField;
            }
            set {
                if ((object.ReferenceEquals(this.PossibleCharactersField, value) != true)) {
                    this.PossibleCharactersField = value;
                    this.RaisePropertyChanged("PossibleCharacters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.SurveyRegionKey RegionKey {
            get {
                return this.RegionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionKeyField, value) != true)) {
                    this.RegionKeyField = value;
                    this.RaisePropertyChanged("RegionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyAnalyseTemplateID {
            get {
                return this.SurveyAnalyseTemplateIDField;
            }
            set {
                if ((this.SurveyAnalyseTemplateIDField.Equals(value) != true)) {
                    this.SurveyAnalyseTemplateIDField = value;
                    this.RaisePropertyChanged("SurveyAnalyseTemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TopLeft_x {
            get {
                return this.TopLeft_xField;
            }
            set {
                if ((this.TopLeft_xField.Equals(value) != true)) {
                    this.TopLeft_xField = value;
                    this.RaisePropertyChanged("TopLeft_x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TopLeft_y {
            get {
                return this.TopLeft_yField;
            }
            set {
                if ((this.TopLeft_yField.Equals(value) != true)) {
                    this.TopLeft_yField = value;
                    this.RaisePropertyChanged("TopLeft_y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.TypeOfRegion TypeOfRegion {
            get {
                return this.TypeOfRegionField;
            }
            set {
                if ((this.TypeOfRegionField.Equals(value) != true)) {
                    this.TypeOfRegionField = value;
                    this.RaisePropertyChanged("TypeOfRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InquiryStroke", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Inquirys")]
    [System.SerializableAttribute()]
    public partial class InquiryStroke : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime createDateTimeField;
        
        private int idInquiryDBInfoField;
        
        private int inquiryPartField;
        
        private BPBzadanie1.ServiceReference1.InquiryPoint inquiryPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime createDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                if ((this.createDateTimeField.Equals(value) != true)) {
                    this.createDateTimeField = value;
                    this.RaisePropertyChanged("createDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idInquiryDBInfo {
            get {
                return this.idInquiryDBInfoField;
            }
            set {
                if ((this.idInquiryDBInfoField.Equals(value) != true)) {
                    this.idInquiryDBInfoField = value;
                    this.RaisePropertyChanged("idInquiryDBInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int inquiryPart {
            get {
                return this.inquiryPartField;
            }
            set {
                if ((this.inquiryPartField.Equals(value) != true)) {
                    this.inquiryPartField = value;
                    this.RaisePropertyChanged("inquiryPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BPBzadanie1.ServiceReference1.InquiryPoint inquiryPoints {
            get {
                return this.inquiryPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.inquiryPointsField, value) != true)) {
                    this.inquiryPointsField = value;
                    this.RaisePropertyChanged("inquiryPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyRegionKey", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Survey")]
    [System.SerializableAttribute()]
    public partial class SurveyRegionKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExportToPDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxSelectedCheckboxesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PointAllValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BPBzadanie1.ServiceReference1.SurveyRegionKeyValue[] SurveyRegionKeyValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExportToPDF {
            get {
                return this.ExportToPDFField;
            }
            set {
                if ((this.ExportToPDFField.Equals(value) != true)) {
                    this.ExportToPDFField = value;
                    this.RaisePropertyChanged("ExportToPDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxSelectedCheckboxes {
            get {
                return this.MaxSelectedCheckboxesField;
            }
            set {
                if ((this.MaxSelectedCheckboxesField.Equals(value) != true)) {
                    this.MaxSelectedCheckboxesField = value;
                    this.RaisePropertyChanged("MaxSelectedCheckboxes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PointAllValues {
            get {
                return this.PointAllValuesField;
            }
            set {
                if ((this.PointAllValuesField.Equals(value) != true)) {
                    this.PointAllValuesField = value;
                    this.RaisePropertyChanged("PointAllValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegionID {
            get {
                return this.RegionIDField;
            }
            set {
                if ((this.RegionIDField.Equals(value) != true)) {
                    this.RegionIDField = value;
                    this.RaisePropertyChanged("RegionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BPBzadanie1.ServiceReference1.SurveyRegionKeyValue[] SurveyRegionKeyValues {
            get {
                return this.SurveyRegionKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyRegionKeyValuesField, value) != true)) {
                    this.SurveyRegionKeyValuesField = value;
                    this.RaisePropertyChanged("SurveyRegionKeyValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeOfRegion", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Enums")]
    public enum TypeOfRegion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        checkBox = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        textBox = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        numericalBox = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        openAnswer = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        anotoSmallSign = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        surveyNumberAndInquirynumber = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        trainingTextBox = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        trainingNumericalBox = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        regionWithoutPattern = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pairWithPc = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pairWithMobile = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sendToPc = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sendToMobile = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        imageRegion = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        textBoxSerie = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        signature = 15,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyRegionKeyValue", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Survey")]
    [System.SerializableAttribute()]
    public partial class SurveyRegionKeyValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeyPoints {
            get {
                return this.KeyPointsField;
            }
            set {
                if ((this.KeyPointsField.Equals(value) != true)) {
                    this.KeyPointsField = value;
                    this.RaisePropertyChanged("KeyPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyValue {
            get {
                return this.KeyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyValueField, value) != true)) {
                    this.KeyValueField = value;
                    this.RaisePropertyChanged("KeyValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InquiryPoint", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Inquirys")]
    [System.SerializableAttribute()]
    public partial class InquiryPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private BPBzadanie1.ServiceReference1.Point[] pointsListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BPBzadanie1.ServiceReference1.Point[] pointsList {
            get {
                return this.pointsListField;
            }
            set {
                if ((object.ReferenceEquals(this.pointsListField, value) != true)) {
                    this.pointsListField = value;
                    this.RaisePropertyChanged("pointsList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="http://schemas.datacontract.org/2004/07/ICPen2.DataModels.Commons")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Deltak__BackingFieldField;
        
        private byte forceField;
        
        private float xField;
        
        private float yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Delta>k__BackingField", IsRequired=true)]
        public int Deltak__BackingField {
            get {
                return this.Deltak__BackingFieldField;
            }
            set {
                if ((this.Deltak__BackingFieldField.Equals(value) != true)) {
                    this.Deltak__BackingFieldField = value;
                    this.RaisePropertyChanged("Deltak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte force {
            get {
                return this.forceField;
            }
            set {
                if ((this.forceField.Equals(value) != true)) {
                    this.forceField = value;
                    this.RaisePropertyChanged("force");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.PPBService")]
    public interface PPBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPBService/GetSignatures", ReplyAction="http://tempuri.org/PPBService/GetSignaturesResponse")]
        BPBzadanie1.ServiceReference1.RegionsWithStrokesObject GetSignatures(string login, string pass, int printInfoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PPBService/GetSignatures", ReplyAction="http://tempuri.org/PPBService/GetSignaturesResponse")]
        System.Threading.Tasks.Task<BPBzadanie1.ServiceReference1.RegionsWithStrokesObject> GetSignaturesAsync(string login, string pass, int printInfoID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PPBServiceChannel : BPBzadanie1.ServiceReference1.PPBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PPBServiceClient : System.ServiceModel.ClientBase<BPBzadanie1.ServiceReference1.PPBService>, BPBzadanie1.ServiceReference1.PPBService {
        
        public PPBServiceClient() {
        }
        
        public PPBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PPBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PPBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BPBzadanie1.ServiceReference1.RegionsWithStrokesObject GetSignatures(string login, string pass, int printInfoID) {
            return base.Channel.GetSignatures(login, pass, printInfoID);
        }
        
        public System.Threading.Tasks.Task<BPBzadanie1.ServiceReference1.RegionsWithStrokesObject> GetSignaturesAsync(string login, string pass, int printInfoID) {
            return base.Channel.GetSignaturesAsync(login, pass, printInfoID);
        }
    }
}
